SELECT TO_DATE('12/11/2019' , 'DD/MM/YYYY') FROM dual;

SELECT TO_DATE('12/11/2019' , 'MM/DD/YYYY') FROM dual;

SELECT TO_CHAR(SYSDATE, 'MM/DD/YYYY HH12:MM:SS AM') FROM DUAL;

SELECT EXTRACT(MONTH FROM TO_DATE('12/11/2019' , 'DD/MM/YYYY')) FROM dual;

SELECT EXTRACT(MONTH FROM TO_DATE('12/11/2019' , 'MM/DD/YYYY')) FROM dual;

SELECT TO_NUMBER('10') + 100 FROM DUAL;

SELECT TO_CHAR(10, '00000') FROM dual;

SELECT NVL(10,0) FROM DUAL;


SELECT TABELA_DE_VENDEDORES.NOME AS NOME_VENDEDOR
, TABELA_DE_VENDEDORES.BAIRRO AS BAIRRO_VENDEDOR
, TABELA_DE_CLIENTES.NOME AS NOME_CLIENTE
, TABELA_DE_CLIENTES.BAIRRO AS BAIRRO_CLIENTE
FROM TABELA_DE_VENDEDORES
FULL JOIN TABELA_DE_CLIENTES
ON TABELA_DE_VENDEDORES.BAIRRO = TABELA_DE_CLIENTES.BAIRRO;

SELECT NVL(TABELA_DE_VENDEDORES.NOME, 'Vendedor Vazio') AS NOME_VENDEDOR
, TABELA_DE_VENDEDORES.BAIRRO AS BAIRRO_VENDEDOR
, TABELA_DE_CLIENTES.NOME AS NOME_CLIENTE
, TABELA_DE_CLIENTES.BAIRRO AS BAIRRO_CLIENTE
FROM TABELA_DE_VENDEDORES
FULL JOIN TABELA_DE_CLIENTES
ON TABELA_DE_VENDEDORES.BAIRRO = TABELA_DE_CLIENTES.BAIRRO;


SELECT GREATEST(10,20,15) FROM DUAL;


SELECT VOLUME_DE_COMPRA, LIMITE_DE_CREDITO, 
GREATEST(VOLUME_DE_COMPRA,LIMITE_DE_CREDITO) MAIOR
FROM TABELA_DE_CLIENTES;


SELECT * FROM tabela_de_clientes;

SELECT 'O cliente' || ' ' || tc.nome || ' faturou' || '    ' || TO_CHAR(ROUND(SUM(inf.QUANTIDADE * inf.preco),2)) || 
' no ano de 2016'
FROM notas_fiscais nf
JOIN itens_notas_fiscais inf
ON nf.numero = inf.numero
JOIN tabela_de_clientes tc
ON nf.cpf = tc.cpf
WHERE TO_CHAR(DATA_VENDA, 'YYYY') = '2016'
GROUP BY tc.CPF, tc.NOME, TO_CHAR(DATA_VENDA, 'YYYY')
ORDER BY tc.NOME






